
version: "3.5"
services :
  # API Proxy
  proxy:
    image: "haproxy"
    ports:
      - 8080:8080
      - 8081:8081
    volumes:
      - ./haproxy:/usr/local/etc/haproxy
    depends_on:
      - ws1
      - ws2
      - ws3
      - frontend1
      - frontend2
    networks:
      - node_network

  # Used by chat pub-sub
  rds:
    image: "redis"
    networks:
      - node_network

  # WebSockets server
  ws1:
    build:
      context: ./socket
      dockerfile: Dockerfile
    environment:
      - mongo_server=mongo
      - ID=1
    depends_on:
      - mongo
    networks:
      - node_network
  ws2:
    build:
      context: ./socket
      dockerfile: Dockerfile
    environment:
      - mongo_server=mongo
      - ID=2 
    depends_on:
      - mongo
    networks:
      - node_network
  ws3:
    build:
      context: ./socket
      dockerfile: Dockerfile
    environment:
      - mongo_server=mongo
      - ID=3
    depends_on:
      - mongo
    networks:
      - node_network

  # Document db to store chat messages
  # <TODO> move to Cassandra
  mongo:
    image: "mongo"
    volumes:
      - dbdata:/data/db
    networks:
      - node_network
    expose:
      - 27017

  # Frontend clients serving REST API and UI.
  frontend1:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - mongo_server=mongo
      - ID=1
    depends_on:
      - mongo
    networks:
      - node_network
    links:
      - mongo
    # waiting for server to start...
    # command: sh -c '/bin/wait-for-it.sh rabbitmq:5672 --timeout=30 -- npm run frontend'

  frontend2:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - mongo_server=mongo
      - ID=2
    depends_on:
      - mongo
    networks:
      - node_network
    links:
      - mongo
    # waiting for rabbitmq to start...
    # command: sh -c '/bin/wait-for-it.sh rabbitmq:5672 --timeout=30 -- npm run frontend'

volumes:
  dbdata:

networks:
  node_network:
    driver: bridge
