version: "3.5"
services :
  proxy:
    image: "haproxy"
    ports:
      - 8080:8080
    volumes:
      - ./haproxy:/usr/local/etc/haproxy
  rds:
    image: "redis"
  ws1:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - ID=1
  ws2:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - ID=2 
  ws3:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - ID=3
